'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';

export default function MobileLogin() {
  const router = useRouter();
  const [phoneNumber, setPhoneNumber] = useState('');
  const [otpCode, setOtpCode] = useState('');
  const [step, setStep] = useState(1); // 1 = Phone Input, 2 = OTP Input
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  const [simulatedOtp, setSimulatedOtp] = useState('');

  const handleRequestOtp = (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    // Basic Thai phone number regex validation
    const cleanPhone = phoneNumber.replace(/[^0-9]/g, '');
    if (cleanPhone.length !== 10 || !cleanPhone.startsWith('0')) {
      setError('กรุณากรอกเบอร์โทรศัพท์มือถือ 10 หลักให้ถูกต้อง (เช่น 0812345678)');
      return;
    }

    setIsLoading(true);

    // Simulate API request to SMS Gateway
    setTimeout(() => {
      setIsLoading(false);
      setStep(2);
      // Simulate code generated by server
      const code = Math.floor(100000 + Math.random() * 900000).toString();
      setSimulatedOtp(code);
    }, 1200);
  };

  const handleVerifyOtp = (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (otpCode.length !== 6) {
      setError('กรุณากรอกรหัส OTP 6 หลัก');
      return;
    }

    setIsLoading(true);

    setTimeout(() => {
      setIsLoading(false);
      // Check code or simulate correct login
      if (otpCode === simulatedOtp || otpCode === '123456') {
        // Successful login -> Redirect to Backoffice manage page
        router.push('/manage');
      } else {
        setError('รหัส OTP ไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง');
      }
    }, 1000);
  };

  return (
    <main className="min-h-screen bg-slate-950 text-slate-100 flex items-center justify-center p-4 relative overflow-hidden">
      {/* Decorative Glow */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[350px] h-[350px] bg-emerald-500/5 rounded-full blur-[80px] pointer-events-none" />

      {/* Centered Mobile Login Card wrapper */}
      <div className="w-full max-w-md p-8 rounded-3xl border border-slate-900 bg-slate-900/40 backdrop-blur-md shadow-2xl relative z-10 space-y-8">
        <header className="text-center space-y-2">
          <span className="text-[10px] uppercase font-black text-emerald-400 tracking-widest bg-emerald-500/10 px-3 py-1 rounded-full">
            FOREVER LOGIN
          </span>
          <h1 className="text-2xl font-black text-white pt-2">
            เข้าสู่ระบบด้วยเบอร์มือถือ
          </h1>
          <p className="text-slate-400 text-xs leading-relaxed max-w-xs mx-auto">
            เพื่อความปลอดภัยสูงสุดและง่ายดายสำหรับผู้สูงอายุ ระบบจะส่งรหัสความปลอดภัยเข้าเบอร์มือถือของคุณโดยไม่ต้องใช้รหัสผ่าน
          </p>
        </header>

        {error && (
          <div className="p-4 rounded-2xl bg-red-500/10 border border-red-500/20 text-xs text-red-400 text-center font-medium">
            ⚠️ {error}
          </div>
        )}

        {/* STEP 1: Phone number input form */}
        {step === 1 && (
          <form onSubmit={handleRequestOtp} className="space-y-6">
            <div className="space-y-2">
              <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider block">
                เบอร์โทรศัพท์มือถือ
              </label>
              <input 
                type="tel"
                value={phoneNumber}
                onChange={(e) => setPhoneNumber(e.target.value)}
                placeholder="ตัวอย่าง 0812345678"
                maxLength={10}
                className="w-full px-5 py-3.5 bg-slate-950 border border-slate-800 rounded-2xl text-white font-mono placeholder-slate-600 focus:outline-none focus:border-emerald-500 transition text-base"
                disabled={isLoading}
              />
            </div>

            <button 
              type="submit" 
              className="w-full py-4 rounded-2xl bg-gradient-to-r from-emerald-500 to-teal-500 text-slate-950 font-bold hover:brightness-110 active:scale-[0.98] transition shadow-[0_0_20px_rgba(16,185,129,0.2)] disabled:opacity-50"
              disabled={isLoading}
            >
              {isLoading ? 'กำลังส่งคำขอ...' : 'รับรหัส OTP ผ่าน SMS'}
            </button>
          </form>
        )}

        {/* STEP 2: OTP verification input form */}
        {step === 2 && (
          <form onSubmit={handleVerifyOtp} className="space-y-6">
            <div className="space-y-2">
              <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider block">
                ป้อนรหัส OTP 6 หลัก
              </label>
              <input 
                type="text"
                pattern="[0-9]*"
                inputMode="numeric"
                maxLength={6}
                value={otpCode}
                onChange={(e) => setOtpCode(e.target.value.replace(/[^0-9]/g, ''))}
                placeholder="123456"
                className="w-full px-5 py-3.5 bg-slate-950 border border-slate-800 rounded-2xl text-white font-mono text-center tracking-[0.7em] text-xl placeholder-slate-800 focus:outline-none focus:border-emerald-500 transition"
                disabled={isLoading}
              />
              <p className="text-[10px] text-slate-500 text-center">
                * ระบบส่งรหัสไปยังเบอร์ {phoneNumber} แล้ว
              </p>
            </div>

            {/* Simulated OTP Banner */}
            <div className="p-4 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 text-center space-y-1">
              <p className="text-[10px] text-emerald-400 font-bold">📲 (จำลองการรับข้อความจากโครงข่าย)</p>
              <p className="text-xs text-white font-mono">
                รหัสความทรงจำของคุณคือ: <span className="font-bold underline text-sm tracking-wide">{simulatedOtp}</span>
              </p>
            </div>

            <button 
              type="submit" 
              className="w-full py-4 rounded-2xl bg-gradient-to-r from-emerald-500 to-teal-500 text-slate-950 font-bold hover:brightness-110 active:scale-[0.98] transition shadow-[0_0_20px_rgba(16,185,129,0.2)] disabled:opacity-50"
              disabled={isLoading}
            >
              {isLoading ? 'กำลังประมวลผล...' : 'ยืนยันรหัส OTP'}
            </button>

            <button 
              type="button"
              onClick={() => { setStep(1); setOtpCode(''); }}
              className="w-full text-center text-xs text-slate-400 hover:text-slate-200 transition font-medium"
            >
              แก้ไขเบอร์โทรศัพท์
            </button>
          </form>
        )}
      </div>
    </main>
  );
}
